---
- hosts: all
  vars:
    rbenv:
      env: user
      version: v0.4.0
      ruby_version: 2.2.0
    # mailhog_binary_url: https://github.com/mailhog/MailHog/releases/download/v0.1.3/MailHog_linux_amd64
    # mailhog_binary_url: http://10.0.2.2:8080/MailHog_linux_amd64

  # roles:
    # - role: zzet.rbenv
    #   rbenv_users:
    #     - { name: 'vagrant', home: '/home/vagrant', comment: 'vagrant user' }
    # - role: geerlingguy.mailhog
    # - role: geerlingguy.ansible

  # roles:
  #   - zzet.rbenv
  
  tasks:
  #   - apt: update_cache=yes cache_valid_time=3600
  #   - name: Using apt source in mainland
  #     replace: dest=/etc/apt/sources.list regexp='archive.ubuntu.com' replace='mirrors.sohu.com'
  #   - name: Install zh-CN language pack
  #     apt: name=language-pack-zh-hans state=present

  # - git: repo=git://github.com/geerlingguy/ansible-role-ansible.git
  #         dest = /etc/ansible/roles/geerlingguy.ansible
    - apt: name=nginx state=present
